---
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: 
    jsx: true
extends: [prettier, plugin:react/recommended]
plugins: [react, prettier]
settings:
  react:
    version: detect
  linkComponents: [Link]
rules:
  prettier/prettier: error
  react/no-unescaped-entities: off
